name: Build Rootless Tweak

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          brew install dpkg ldid make clang git

      - name: Setup Theos
        run: |
          git clone --depth=1 https://github.com/theos/theos.git theos
          git clone --depth=1 https://github.com/theos/sdks.git theos/sdks
          echo "export THEOS=$(pwd)/theos" >> $GITHUB_ENV

      - name: Clone Cephei fork (no MobileIcons)
        run: |
          git clone --depth=1 https://github.com/opa334/Cephei.git Cephei

      - name: Build Cephei
        run: |
          cd Cephei
          make clean
          make LIBRARIES=Cephei

          mkdir -p ../lib
          cp .theos/obj/debug/arm64/libCephei.a ../lib/

      - name: Build tweak
        run: |
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless

      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: calculatorhistory
          path: ./packages/*.deb
