name: CI

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build.yml'
      - 'control'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install dependencies
        run: |
          brew install dpkg ldid git

      - name: Setup Theos
        run: |
          rm -rf theos
          git clone --depth=1 https://github.com/theos/theos.git theos
          git clone --depth=1 https://github.com/theos/sdks.git theos/sdks
          echo "THEOS=$PWD/theos" >> $GITHUB_ENV

      - name: Clone Cephei fork (no MobileIcons)
        run: |
          git clone --depth=1 https://github.com/opa334/Cephei.git Cephei

      - name: Build Cephei (only libCephei)
        run: |
          cd Cephei
          make clean
          make LIBRARIES=Cephei

          mkdir -p ../lib
          cp .theos/obj/debug/arm64/libCephei.a ../lib/

      - name: Clean previous packages
        run: rm -f ./packages/*.deb || true

      - name: Build tweak and bundle packages
        run: |
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless

      - name: List generated DEBs
        run: ls -lh ./packages

      - name: Create GitHub Release
        if: github.event_name == 'push'
        run: |
          VERSION=$(date +v%Y%m%d%H%M)
          gh release create "$VERSION" ./packages/*.deb --title "calculatorhistory $VERSION" --notes "自动构建 .deb 安装包"
        env:
          GH_TOKEN: ${{ secrets.PAT }}

      - name: Upload DEB to workflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: calculatorhistory
          path: ./packages/*.deb
